name: Deployment Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install python 3.6.8 32-bit and pip
        uses: actions/setup-python@v2
        with:
          python-version: 3.6.8
          architecture: x86
      - name: Linter
        run: |
          pip install pylint
          pylint __init__.py --disable=invalid-name --output-format=colorized