name: Approve pull request
on:
  pull_request:
    branches:
      - qa
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python 3.10 64-bit
      uses: actions/setup-python@v2
      with:
        python-version: 3.10
        architecture: x64
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install pytest
    - name: Lint with pylint
      run: |
        if [ -d "tests" ]; then
          pylint --rcfile=.pylintrc tests
        fi
    - name: Run pytest
      run: |
        if [ -d "tests" ]; then
          pytest tests/
        fi
    - name: Check for required files and directories
      run: |
        if [ -f "__init__.py" ]; then
          echo "__init__.py found."
        else
          echo "__init__.py not found. Exiting."
          exit 1
        fi
        if [ -f "package.json" ]; then
          echo "package.json found."
        else
          echo "package.json not found. Exiting."
          exit 1
        fi
        if [ -f "readme.md" ]; then
          echo "readme.md found."
        else
          echo "readme.md not found. Exiting."
          exit 1
        fi
        if [ -d "docs" ]; then
          echo "docs directory found."
        else
          echo "docs directory not found. Exiting."
          exit 1
        fi
        if [ -d "example" ]; then
          echo "example directory found."
        else
          echo "example directory not found. Exiting."
          exit 1
        fi
